agent_type: medical_triage
base_model: TinyLlama/TinyLlama-1.1B-Chat-v1.0
embedding_model: sentence-transformers/all-MiniLM-L6-v2
max_token_limit: 1024
safety_checks:
  - bias_detection
  - phi_redaction
rag:
  chunk_size: 512
  similarity_top_k: 3
  vector_store: chroma-memory
prompt_template: |
  As a {agent_role}, analyze this input:
  {user_input}
  
  Consider:
  - {consideration_points}
  
  Respond using JSON format:
  {response_format}